# Generated by Django 6.0.5 on 2026-07-01 01:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calibracao', '0025_instrumento_tag'),
        ('clientes', '0002_alter_perfilusuario_empresa'),
        ('comercial', '0002_alter_crmregistro_options_alter_crmticket_options_and_more'),
        ('qualidade', '0002_alter_documento_options_documento_aprovado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanhaMarketing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('trafego_pago', 'Trafego pago'), ('outro', 'Outro')], default='instagram', max_length=30)),
                ('objetivo', models.TextField(blank=True)),
                ('publico_alvo', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('em_criacao', 'Em criacao'), ('aguardando_aprovacao', 'Aguardando aprovacao'), ('aprovada', 'Aprovada'), ('publicada', 'Publicada'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada'), ('arquivada', 'Arquivada')], default='planejada', max_length=30)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_final', models.DateField(blank=True, null=True)),
                ('orcamento', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produto_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanhas_marketing', to='comercial.produtoservico')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanhas_marketing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marketing - Campanha',
                'verbose_name_plural': 'Marketing - Campanhas',
                'ordering': ('-created_at', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('equipamento', 'Equipamento'), ('servico', 'Servico'), ('metodo', 'Metodo'), ('automacao', 'Automacao'), ('retrofit', 'Retrofit'), ('produto', 'Produto'), ('software', 'Software'), ('melhoria_interna', 'Melhoria interna'), ('outro', 'Outro')], default='equipamento', max_length=30)),
                ('area', models.CharField(choices=[('calibracao', 'Calibracao'), ('manutencao', 'Manutencao'), ('vendas', 'Vendas'), ('qualidade', 'Qualidade'), ('software', 'Software'), ('marketing', 'Marketing'), ('interno', 'Interno')], default='calibracao', max_length=30)),
                ('status', models.CharField(choices=[('ideia', 'Ideia'), ('em_analise', 'Em analise'), ('aprovado_desenvolvimento', 'Aprovado para desenvolvimento'), ('em_desenvolvimento', 'Em desenvolvimento'), ('aguardando_compra', 'Aguardando compra'), ('em_teste', 'Em teste'), ('em_validacao', 'Em validacao'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('cancelado', 'Cancelado'), ('liberado_comercialmente', 'Liberado comercialmente')], default='ideia', max_length=40)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('objetivo', models.TextField(blank=True)),
                ('justificativa', models.TextField(blank=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('previsao_conclusao', models.DateField(blank=True, null=True)),
                ('orcamento_previsto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('custo_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('resultado_esperado', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_desenvolvimento', to='clientes.cliente')),
                ('produto_servico_gerado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_origem', to='comercial.produtoservico')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Desenvolvimento Tecnico - Projeto',
                'verbose_name_plural': 'Desenvolvimento Tecnico - Projetos',
                'ordering': ('-created_at', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='MidiaMarketing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Video'), ('logo', 'Logo'), ('arte', 'Arte'), ('documento', 'Documento')], default='imagem', max_length=20)),
                ('categoria', models.CharField(choices=[('institucional', 'Institucional'), ('calibracao', 'Calibracao'), ('manutencao', 'Manutencao'), ('equipamentos', 'Equipamentos'), ('antes_depois', 'Antes e depois'), ('bastidores', 'Bastidores'), ('clientes', 'Clientes'), ('treinamentos', 'Treinamentos'), ('posts_prontos', 'Posts prontos'), ('stories', 'Stories'), ('videos_tecnicos', 'Videos tecnicos'), ('logos', 'Logos e identidade visual')], default='institucional', max_length=30)),
                ('canal_sugerido', models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('site', 'Site'), ('outro', 'Outro')], default='instagram', max_length=20)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('uso_autorizado', models.BooleanField(default=True)),
                ('arquivo', models.FileField(upload_to='projetos/marketing/')),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campanha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='midias', to='projetos.campanhamarketing')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='midias_marketing', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='midias_marketing', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Marketing - Biblioteca de midia',
                'verbose_name_plural': 'Marketing - Biblioteca de midias',
                'ordering': ('-created_at', 'titulo'),
            },
        ),
        migrations.AddField(
            model_name='campanhamarketing',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanhas_marketing', to='projetos.projeto'),
        ),
        migrations.CreateModel(
            name='ProjetoArquivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('tipo_arquivo', models.CharField(choices=[('foto', 'Foto'), ('video', 'Video'), ('pdf', 'PDF'), ('manual', 'Manual'), ('orcamento', 'Orcamento'), ('nota_fiscal', 'Nota fiscal'), ('desenho_tecnico', 'Desenho tecnico'), ('planilha', 'Planilha'), ('certificado', 'Certificado'), ('relatorio', 'Relatorio'), ('imagem_marketing', 'Imagem para marketing'), ('outro', 'Outro')], default='outro', max_length=30)),
                ('arquivo', models.FileField(upload_to='projetos/arquivos/')),
                ('descricao', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='projetos.projeto')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos_projeto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Desenvolvimento Tecnico - Arquivo do projeto',
                'verbose_name_plural': 'Desenvolvimento Tecnico - Arquivos do projeto',
                'ordering': ('projeto__codigo', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProjetoCusto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('custo_componentes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('horas_tecnicas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_hora_tecnica', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo_outros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('preco_estimado_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payback_esperado', models.CharField(blank=True, max_length=120)),
                ('viabilidade', models.CharField(choices=[('em_analise', 'Em analise'), ('viavel', 'Viavel'), ('nao_viavel', 'Nao viavel')], default='em_analise', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Desenvolvimento Tecnico - Custo e viabilidade',
                'verbose_name_plural': 'Desenvolvimento Tecnico - Custos e viabilidade',
                'ordering': ('projeto__codigo', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProjetoTarefa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('a_fazer', 'A fazer'), ('em_andamento', 'Em andamento'), ('em_teste', 'Em teste'), ('aguardando_compra', 'Aguardando compra'), ('concluido', 'Concluido')], default='a_fazer', max_length=30)),
                ('observacao', models.TextField(blank=True)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='projetos/tarefas/')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='projetos.projeto')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_projeto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Desenvolvimento Tecnico - Etapa/Tarefa',
                'verbose_name_plural': 'Desenvolvimento Tecnico - Etapas/Tarefas',
                'ordering': ('projeto__codigo', 'ordem', 'prazo'),
            },
        ),
        migrations.CreateModel(
            name='ProjetoTeste',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_teste', models.CharField(max_length=120)),
                ('data_teste', models.DateField()),
                ('condicao_ambiental', models.CharField(blank=True, max_length=120)),
                ('resultado', models.CharField(choices=[('aprovado', 'Aprovado'), ('aprovado_restricao', 'Aprovado com restricao'), ('reprovado', 'Reprovado'), ('em_analise', 'Em analise')], default='em_analise', max_length=30)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='projetos/testes/')),
                ('observacao_tecnica', models.TextField(blank=True)),
                ('conclusao_tecnica', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documento_tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testes_projeto', to='qualidade.documento')),
                ('padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testes_projeto', to='calibracao.padrao')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testes', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Desenvolvimento Tecnico - Teste e validacao',
                'verbose_name_plural': 'Desenvolvimento Tecnico - Testes e validacoes',
                'ordering': ('-data_teste', 'tipo_teste'),
            },
        ),
    ]
