# Generated by Django 6.0.5 on 2026-06-09 21:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calibracao', '0014_responsavelcertificado_and_more'),
        ('clientes', '0001_initial'),
        ('comercial', '0002_alter_crmregistro_options_alter_crmticket_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanejamentoServico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Codigo')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Titulo do planejamento')),
                ('tipo_agendamento', models.CharField(choices=[('servico', 'Servico programado'), ('visita_tecnica', 'Agendamento de visita'), ('retirada', 'Retirada de equipamento'), ('entrega', 'Entrega de equipamento'), ('coleta', 'Coleta externa'), ('outro', 'Outro')], default='servico', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('em_execucao', 'Em execucao'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], default='agendado', max_length=20)),
                ('telefone_contato', models.CharField(blank=True, max_length=30, verbose_name='Telefone do contato')),
                ('email_contato', models.EmailField(blank=True, max_length=254, verbose_name='E-mail do contato')),
                ('data_inicio', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data inicial')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data final')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora inicial')),
                ('hora_fim', models.TimeField(blank=True, null=True, verbose_name='Hora final')),
                ('dia_inteiro', models.BooleanField(default=False, verbose_name='Dia inteiro')),
                ('confirmado_cliente', models.BooleanField(default=False, verbose_name='Cliente confirmado')),
                ('local_servico', models.CharField(blank=True, max_length=255, verbose_name='Local do servico')),
                ('necessita_veiculo', models.BooleanField(default=False, verbose_name='Necessita carro')),
                ('veiculo_descricao', models.CharField(blank=True, max_length=120, verbose_name='Veiculo previsto')),
                ('recursos_necessarios', models.TextField(blank=True, help_text='Ex.: notebook, EPI, ferramental, etiquetas, formulario, impressora.', verbose_name='Recursos necessarios')),
                ('retirada_equipamentos', models.TextField(blank=True, help_text='Descreva o que sera retirado, entregue ou movimentado.', verbose_name='Retirada/entrega de equipamentos')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planejamentos_servico', to='clientes.cliente', verbose_name='Cliente')),
                ('contato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planejamentos_servico', to='clientes.contatocliente', verbose_name='Contato')),
                ('instrumentos', models.ManyToManyField(blank=True, related_name='planejamentos_servico', to='calibracao.instrumento', verbose_name='Equipamentos previstos')),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planejamentos_servico', to='calibracao.ordemservico', verbose_name='Ordem de Servico')),
                ('padroes', models.ManyToManyField(blank=True, related_name='planejamentos_servico', to='calibracao.padrao', verbose_name='Padroes necessarios')),
                ('proposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planejamentos_servico', to='comercial.proposta', verbose_name='Proposta')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planejamentos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsavel pelo planejamento')),
                ('tecnicos', models.ManyToManyField(blank=True, related_name='planejamentos_tecnicos', to=settings.AUTH_USER_MODEL, verbose_name='Equipe tecnica')),
            ],
            options={
                'verbose_name': 'Planejamento de Servico',
                'verbose_name_plural': 'Planejamentos de Servico',
                'ordering': ('data_inicio', 'hora_inicio', 'cliente__razao_social'),
            },
        ),
    ]
