# Generated by Django 6.0.5 on 2026-06-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamentoservico',
            name='padroes_obrigatorios',
            field=models.BooleanField(default=True, verbose_name='Exigir padroes para o servico'),
        ),
        migrations.AddField(
            model_name='planejamentoservico',
            name='responsavel_cliente_cargo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Cargo do responsavel do cliente'),
        ),
        migrations.AddField(
            model_name='planejamentoservico',
            name='responsavel_cliente_nome',
            field=models.CharField(blank=True, max_length=150, verbose_name='Responsavel do cliente'),
        ),
    ]
