# Generated by Django 6.0.5 on 2026-06-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0002_planejamentoservico_padroes_obrigatorios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planejamentoservico',
            name='padroes_obrigatorios',
        ),
        migrations.RemoveField(
            model_name='planejamentoservico',
            name='responsavel_cliente_cargo',
        ),
        migrations.RemoveField(
            model_name='planejamentoservico',
            name='responsavel_cliente_nome',
        ),
        migrations.AlterField(
            model_name='planejamentoservico',
            name='tipo_agendamento',
            field=models.CharField(choices=[('servico', 'Servico agendado'), ('visita_tecnica', 'Agendamento de visita'), ('retirada', 'Retirada de equipamento'), ('entrega', 'Entrega de equipamento'), ('coleta', 'Coleta externa'), ('outro', 'Outro')], default='servico', max_length=20, verbose_name='Tipo'),
        ),
    ]
