# Generated by Django 6.0.5 on 2026-07-02 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0003_remove_planejamentoservico_padroes_obrigatorios_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planejamentoservico',
            options={'ordering': ('data_inicio', 'hora_inicio', 'cliente__razao_social'), 'verbose_name': 'Agenda técnica', 'verbose_name_plural': 'Agendas técnicas'},
        ),
    ]
