# Generated by Django 6.0.5 on 2026-07-05 05:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_perfilusuario_empresa'),
        ('planejamento', '0004_alter_planejamentoservico_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioEquipamentoSemNota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Codigo')),
                ('data_envio_formulario', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data de envio')),
                ('empresa_remetente', models.CharField(blank=True, max_length=255, verbose_name='Empresa remetente')),
                ('cnpj_cpf_remetente', models.CharField(blank=True, max_length=20, verbose_name='CNPJ/CPF')),
                ('endereco_remetente', models.CharField(blank=True, max_length=255, verbose_name='Endereco')),
                ('cidade_uf_remetente', models.CharField(blank=True, max_length=120, verbose_name='Cidade/UF')),
                ('responsavel_envio', models.CharField(blank=True, max_length=120, verbose_name='Responsavel pelo envio')),
                ('telefone_whatsapp', models.CharField(blank=True, max_length=30, verbose_name='Telefone/WhatsApp')),
                ('email_remetente', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('empresa_destinataria', models.CharField(default='DS Cientifica', max_length=255, verbose_name='Empresa destinataria')),
                ('cnpj_destinatario', models.CharField(blank=True, max_length=20, verbose_name='CNPJ destinatario')),
                ('endereco_destinatario', models.CharField(blank=True, max_length=255, verbose_name='Endereco destinatario')),
                ('cidade_uf_destinatario', models.CharField(blank=True, max_length=120, verbose_name='Cidade/UF destinatario')),
                ('responsavel_recebimento_destino', models.CharField(blank=True, max_length=120, verbose_name='Responsavel pelo recebimento')),
                ('finalidade', models.CharField(choices=[('calibracao', 'Calibracao'), ('manutencao_preventiva', 'Manutencao preventiva'), ('manutencao_corretiva', 'Manutencao corretiva'), ('avaliacao_tecnica', 'Avaliacao tecnica / diagnostico'), ('orcamento', 'Orcamento'), ('outro', 'Outro')], max_length=30, verbose_name='Finalidade do envio')),
                ('finalidade_outro', models.CharField(blank=True, max_length=255, verbose_name='Outro motivo')),
                ('descricao_solicitacao', models.TextField(blank=True, help_text='Descreva o servico solicitado, pontos de calibracao, faixa de uso, defeito apresentado ou informacoes relevantes.', verbose_name='Descricao da solicitacao')),
                ('condicao_funcionamento', models.CharField(blank=True, choices=[('funcionando', 'Equipamento funcionando normalmente'), ('defeito', 'Equipamento com defeito'), ('liga_falha', 'Equipamento liga, mas apresenta falha'), ('nao_liga', 'Equipamento nao liga')], max_length=20, verbose_name='Condicao de funcionamento')),
                ('condicao_acessorios', models.CharField(blank=True, choices=[('com_acessorios', 'Equipamento enviado com acessorios'), ('sem_acessorios', 'Equipamento enviado sem acessorios')], max_length=20, verbose_name='Acessorios')),
                ('condicao_embalagem_envio', models.CharField(blank=True, choices=[('integra', 'Embalagem integra'), ('danificada', 'Embalagem danificada')], max_length=20, verbose_name='Condicao da embalagem')),
                ('acessorios_enviados', models.TextField(blank=True, verbose_name='Acessorios enviados')),
                ('observacoes_estado', models.TextField(blank=True, verbose_name='Observacoes sobre o estado do equipamento')),
                ('transportadora', models.CharField(blank=True, max_length=255, verbose_name='Transportadora / Correios / Portador')),
                ('codigo_rastreamento', models.CharField(blank=True, max_length=120, verbose_name='Codigo de rastreamento')),
                ('data_envio_transporte', models.DateField(blank=True, null=True, verbose_name='Data do envio no transporte')),
                ('responsavel_frete', models.CharField(choices=[('remetente', 'Remetente'), ('destinatario', 'Destinatario'), ('combinar', 'A combinar')], default='remetente', max_length=20, verbose_name='Responsavel pelo frete')),
                ('nome_declarante', models.CharField(blank=True, max_length=120, verbose_name='Nome do responsavel')),
                ('cargo_declarante', models.CharField(blank=True, max_length=120, verbose_name='Cargo')),
                ('cpf_declarante', models.CharField(blank=True, max_length=20, verbose_name='CPF')),
                ('assinatura_declarante', models.CharField(blank=True, help_text='Campo textual para identificacao do assinante no PDF.', max_length=255, verbose_name='Assinatura')),
                ('data_declaracao', models.DateField(blank=True, null=True, verbose_name='Data da declaracao')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='Data de recebimento')),
                ('recebido_por', models.CharField(blank=True, max_length=120, verbose_name='Recebido por')),
                ('condicao_embalagem_recebimento', models.CharField(blank=True, choices=[('integra', 'Integra'), ('danificada', 'Danificada'), ('violada', 'Violada'), ('molhada', 'Molhada'), ('amassada', 'Amassada'), ('outro', 'Outro')], max_length=20, verbose_name='Condicao da embalagem no recebimento')),
                ('condicao_embalagem_recebimento_outro', models.CharField(blank=True, max_length=255, verbose_name='Outro detalhe da embalagem')),
                ('condicao_aparente_recebimento', models.CharField(blank=True, choices=[('sem_avarias', 'Sem avarias aparentes'), ('com_avarias', 'Com avarias aparentes'), ('divergente', 'Divergente da descricao informada'), ('aguardando_avaliacao', 'Aguardando avaliacao tecnica')], max_length=25, verbose_name='Condicao aparente do equipamento no recebimento')),
                ('observacoes_recebimento', models.TextField(blank=True, verbose_name='Observacoes do recebimento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente_remetente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_sem_nota', to='clientes.cliente', verbose_name='Cliente remetente')),
            ],
            options={
                'verbose_name': 'Envio de equipamento sem NF',
                'verbose_name_plural': 'Envios de equipamento sem NF',
                'ordering': ('-data_envio_formulario', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='EnvioEquipamentoSemNotaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Item')),
                ('equipamento', models.CharField(max_length=255, verbose_name='Equipamento')),
                ('marca', models.CharField(blank=True, max_length=120, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=120, verbose_name='Modelo')),
                ('numero_serie_patrimonio', models.CharField(blank=True, max_length=120, verbose_name='N de serie / patrimonio')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='planejamento.envioequipamentosemnota', verbose_name='Formulario')),
            ],
            options={
                'verbose_name': 'Item do envio sem NF',
                'verbose_name_plural': 'Itens do envio sem NF',
                'ordering': ('ordem', 'equipamento'),
            },
        ),
    ]
