# Generated by Django 6.0.5 on 2026-07-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0005_envioequipamentosemnota_envioequipamentosemnotaitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envioequipamentosemnota',
            options={'ordering': ('-data_envio_formulario', '-created_at'), 'verbose_name': 'Formulario logistico sem NF', 'verbose_name_plural': 'Formularios logisticos sem NF'},
        ),
        migrations.AddField(
            model_name='envioequipamentosemnota',
            name='tipo_formulario',
            field=models.CharField(choices=[('envio', 'Envio'), ('recebimento', 'Recebimento')], default='envio', max_length=20, verbose_name='Tipo do formulario'),
        ),
    ]
