# Generated by Django 6.0.5 on 2026-07-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0006_alter_envioequipamentosemnota_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envioequipamentosemnota',
            name='empresa_destinataria',
            field=models.CharField(blank=True, max_length=255, verbose_name='Empresa destinataria'),
        ),
    ]
