# Generated by Django 6.0.5 on 2026-05-25 03:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('calibracao', 'Calibração'), ('produto', 'Produto'), ('manutencao', 'Manutenção'), ('qualificacao', 'Qualificação')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CRMRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('etapa_funil', models.CharField(choices=[('lead', 'Lead'), ('qualificacao', 'Qualificação'), ('proposta', 'Proposta'), ('negociacao', 'Negociação'), ('fechado', 'Fechado')], default='lead', max_length=20)),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('probabilidade', models.CharField(choices=[('frio', 'Frio (10%)'), ('morno', 'Morno (30%)'), ('quente', 'Quente (60%)'), ('muito_quente', 'Muito quente (90%)')], default='frio', max_length=20)),
                ('probabilidade_numero', models.IntegerField(default=10)),
                ('proxima_acao', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CRMInteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='comercial.crmregistro')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('arquivo', models.FileField(upload_to='produtos/anexos/')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='comercial.produtoservico')),
            ],
        ),
        migrations.CreateModel(
            name='DadosTecnicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.TextField(blank=True)),
                ('padroes', models.TextField(blank=True)),
                ('solucoes', models.TextField(blank=True)),
                ('tempo_medio', models.CharField(blank=True, max_length=100)),
                ('equipamentos_auxiliares', models.TextField(blank=True)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_tecnicos', to='comercial.produtoservico')),
            ],
        ),
        migrations.CreateModel(
            name='ComposicaoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_tecnica', models.DecimalField(decimal_places=2, default=0, help_text='R$/hora', max_digits=10)),
                ('tempo_execucao', models.DecimalField(decimal_places=2, help_text='Horas', max_digits=5)),
                ('custo_logistica', models.DecimalField(decimal_places=2, default=0, help_text='R$', max_digits=10)),
                ('custo_insumos', models.DecimalField(decimal_places=2, default=0, help_text='R$', max_digits=10)),
                ('outros_custos', models.DecimalField(decimal_places=2, default=0, help_text='R$', max_digits=10)),
                ('impostos_percentual', models.DecimalField(decimal_places=2, default=0, help_text='%', max_digits=5)),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=0, help_text='%', max_digits=5)),
                ('preco_calculado', models.DecimalField(decimal_places=2, default=0, help_text='R$', max_digits=10)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='composicao', to='comercial.produtoservico')),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=50, unique=True)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('prazo_pagamento', models.CharField(blank=True, max_length=200)),
                ('local_execucao', models.CharField(choices=[('in_loco', 'IN LOCO'), ('laboratorio', 'DS Científica')], default='laboratorio', max_length=20)),
                ('frete', models.CharField(choices=[('CIF', 'CIF'), ('FOB', 'FOB'), ('NA', 'Não aplicável')], default='NA', max_length=10)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado'), ('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='rascunho', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metodo', models.TextField(blank=True)),
                ('padroes_utilizados', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propostas', to='clientes.cliente')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.contatocliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.produtoservico')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='comercial.proposta')),
            ],
        ),
        migrations.CreateModel(
            name='CRMTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('servico', 'Serviço'), ('produto', 'Produto')], default='servico', max_length=20)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('andamento', 'Em andamento'), ('aguardando', 'Aguardando cliente'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado')], default='aberto', max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20)),
                ('prazo_resposta', models.DateField(blank=True, null=True)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.proposta')),
            ],
        ),
        migrations.AddField(
            model_name='crmregistro',
            name='proposta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.proposta'),
        ),
        migrations.CreateModel(
            name='PropostaAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('arquivo', models.FileField(upload_to='propostas/anexos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='comercial.proposta')),
            ],
        ),
    ]
