# Generated by Django 6.0.5 on 2026-06-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmregistro',
            options={'verbose_name': 'Registro de CRM', 'verbose_name_plural': 'Registros de CRM'},
        ),
        migrations.AlterModelOptions(
            name='crmticket',
            options={'verbose_name': 'Ticket de CRM', 'verbose_name_plural': 'Tickets de CRM'},
        ),
        migrations.AlterModelOptions(
            name='produtoservico',
            options={'verbose_name': 'Produto/Serviço', 'verbose_name_plural': 'Produtos/Serviços'},
        ),
    ]
