# Generated by Django 4.2 on 2026-05-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_produtoservico_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='composicaopreco',
            name='formula_calculo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='composicaopreco',
            name='unidade_medida',
            field=models.CharField(choices=[('un', 'Unidade'), ('serv', 'Serviço'), ('hora', 'Hora'), ('dia', 'Dia'), ('kg', 'Kg'), ('m', 'Metro')], default='serv', max_length=20),
        ),
    ]
