# Generated by Django 6.0.5 on 2026-07-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_alter_crmregistro_options_alter_crmticket_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propostaanexo',
            options={'ordering': ('ordem', 'data_upload', 'nome')},
        ),
        migrations.AddField(
            model_name='propostaanexo',
            name='exibir_no_pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propostaanexo',
            name='legenda',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='propostaanexo',
            name='ordem',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
