# Generated by Django 6.0.5 on 2026-07-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_alter_propostaanexo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostaanexo',
            name='tipo',
            field=models.CharField(choices=[('imagem', 'Imagem'), ('documento', 'Documento'), ('outro', 'Outro')], default='imagem', max_length=20),
        ),
    ]
