# Generated by Django 4.2 on 2026-05-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_composicaopreco_formula_calculo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composicaopreco',
            name='formula_calculo',
        ),
        migrations.RemoveField(
            model_name='composicaopreco',
            name='unidade_medida',
        ),
        migrations.AlterField(
            model_name='composicaopreco',
            name='custo_insumos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='R$', max_digits=10),
        ),
        migrations.AlterField(
            model_name='composicaopreco',
            name='custo_logistica',
            field=models.DecimalField(decimal_places=2, default=0, help_text='R$', max_digits=10),
        ),
        migrations.AlterField(
            model_name='composicaopreco',
            name='hora_tecnica',
            field=models.DecimalField(decimal_places=2, default=0, help_text='R$/hora', max_digits=10),
        ),
        migrations.AlterField(
            model_name='composicaopreco',
            name='impostos_percentual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='%', max_digits=5),
        ),
        migrations.AlterField(
            model_name='composicaopreco',
            name='margem_lucro',
            field=models.DecimalField(decimal_places=2, default=0, help_text='%', max_digits=5),
        ),
        migrations.AlterField(
            model_name='composicaopreco',
            name='outros_custos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='R$', max_digits=10),
        ),
        migrations.AlterField(
            model_name='composicaopreco',
            name='preco_calculado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='R$', max_digits=10),
        ),
        migrations.AlterField(
            model_name='composicaopreco',
            name='tempo_execucao',
            field=models.DecimalField(decimal_places=2, help_text='Horas', max_digits=5),
        ),
    ]
