# Generated by Django 4.2 on 2026-05-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_remove_composicaopreco_formula_calculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoservico',
            name='codigo_personalizado',
            field=models.BooleanField(default=False),
        ),
    ]
