# Generated by Django 4.2 on 2026-05-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_produtoservico_codigo_personalizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtoservico',
            name='codigo_personalizado',
        ),
        migrations.AlterField(
            model_name='produtoservico',
            name='tipo',
            field=models.CharField(choices=[('calibracao', 'Calibração'), ('produto', 'Produto'), ('manutencao', 'Manutenção'), ('qualificacao', 'Qualificação')], max_length=20),
        ),
    ]
