# Generated by Django 6.0.5 on 2026-07-02 05:04

import django.db.models.deletion
from django.db import migrations, models


def vincular_propostas_crm(apps, schema_editor):
    Proposta = apps.get_model("comercial", "Proposta")
    CRMRegistro = apps.get_model("comercial", "CRMRegistro")

    for proposta in Proposta.objects.all():
        crm = None
        if proposta.crm_registro_id:
            continue

        crm = CRMRegistro.objects.filter(proposta=proposta).first()
        if crm:
            proposta.crm_registro_id = crm.id
            proposta.save(update_fields=["crm_registro"])


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_crmregistro_codigo_crmregistro_data_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='crm_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas_vinculadas', to='comercial.crmregistro'),
        ),
        migrations.RunPython(vincular_propostas_crm, migrations.RunPython.noop),
    ]
