# Generated by Django 6.0.5 on 2026-07-02 05:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_proposta_crm_registro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crminteracao',
            options={'verbose_name': 'Atividade comercial', 'verbose_name_plural': 'Atividades comerciais'},
        ),
        migrations.AddField(
            model_name='crminteracao',
            name='tipo',
            field=models.CharField(choices=[('ligacao', 'Liga??o'), ('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('reuniao', 'Reuni?o'), ('outro', 'Outro')], default='ligacao', max_length=20),
        ),
        migrations.AlterField(
            model_name='crminteracao',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
