# Generated by Django 6.0.5 on 2026-07-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0007_alter_crminteracao_options_crminteracao_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crminteracao',
            name='proxima_acao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crminteracao',
            name='resultado',
            field=models.CharField(choices=[('sem_resposta', 'Sem resposta'), ('retornou', 'Retornou'), ('reuniao_agendada', 'Reunião agendada'), ('proposta_enviada', 'Proposta enviada'), ('nao_interessado', 'Não interessado'), ('negociacao', 'Em negociação'), ('fechado', 'Fechado')], default='sem_resposta', max_length=30),
        ),
        migrations.AlterField(
            model_name='crminteracao',
            name='tipo',
            field=models.CharField(choices=[('ligacao', 'Ligação'), ('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('reuniao', 'Reunião'), ('outro', 'Outro')], default='ligacao', max_length=20),
        ),
    ]
