# Generated by Django 6.0.5 on 2026-07-02 05:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_perfilusuario_empresa'),
        ('comercial', '0008_crminteracao_proxima_acao_crminteracao_resultado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspeccaoComercial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_conversao', models.DateTimeField(blank=True, null=True)),
                ('razao_social', models.CharField(max_length=255)),
                ('contato_nome', models.CharField(blank=True, max_length=120)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('origem_lead', models.CharField(choices=[('indicacao', 'Indicação'), ('site', 'Site'), ('telefone', 'Telefone'), ('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('visita', 'Visita'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('segmento', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('tentativa_contato', 'Tentativa de contato'), ('sem_resposta', 'Sem resposta'), ('em_contato', 'Em contato'), ('interessado', 'Interessado'), ('sem_interesse', 'Sem interesse'), ('convertido', 'Convertido em CRM'), ('perdido', 'Perdido')], default='novo', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('convertido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospeccoes_convertidas', to=settings.AUTH_USER_MODEL)),
                ('crm_gerado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospeccoes_origem', to='comercial.crmregistro')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prospecção comercial',
                'verbose_name_plural': 'Prospecções comerciais',
            },
        ),
        migrations.CreateModel(
            name='ProspeccaoInteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ligacao', 'Ligação'), ('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('reuniao', 'Reunião'), ('visita', 'Visita'), ('outro', 'Outro')], default='ligacao', max_length=20)),
                ('resultado', models.CharField(choices=[('sem_resposta', 'Sem resposta'), ('retornou', 'Retornou'), ('reuniao_agendada', 'Reunião agendada'), ('aguardando_retorno', 'Aguardando retorno'), ('interessado', 'Interessado'), ('sem_interesse', 'Sem interesse'), ('convertido', 'Convertido para CRM')], default='sem_resposta', max_length=30)),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('proxima_acao', models.DateTimeField(blank=True, null=True)),
                ('prospeccao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='comercial.prospeccaocomercial')),
            ],
            options={
                'verbose_name': 'Interação de prospecção',
                'verbose_name_plural': 'Interações de prospecção',
            },
        ),
    ]
