# Generated by Django 6.0.5 on 2026-07-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0009_prospeccaocomercial_prospeccaointeracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='resultado_fechamento',
            field=models.CharField(blank=True, choices=[('', 'Não definido'), ('positivo', 'Positivo'), ('negativo', 'Negativo')], default='', max_length=20),
        ),
    ]
