# Generated by Django 6.0.5 on 2026-07-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0010_proposta_resultado_fechamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmregistro',
            name='etapa_funil',
            field=models.CharField(choices=[('lead', 'Lead'), ('qualificacao', 'Qualificação'), ('proposta', 'Proposta'), ('negociacao', 'Negociação'), ('fechado', 'Fechado'), ('fechado_ganho', 'Fechado ganho'), ('fechado_perdido', 'Fechado perdido')], default='lead', max_length=20),
        ),
    ]
