# Generated by Django 6.0.5 on 2026-07-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0011_alter_crmregistro_etapa_funil'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='motivo_perda',
            field=models.CharField(blank=True, choices=[('', 'Não definido'), ('preco', 'Preço'), ('prazo', 'Prazo'), ('escopo', 'Escopo técnico'), ('concorrencia', 'Concorrência'), ('sem_retorno', 'Sem retorno do cliente'), ('orcamento_cancelado', 'Orçamento cancelado pelo cliente'), ('outro', 'Outro')], default='', max_length=30),
        ),
    ]
