# Generated by Django 6.0.5 on 2026-07-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0012_proposta_motivo_perda'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='gera_conta_receber_automaticamente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposta',
            name='revisao',
            field=models.CharField(blank=True, default='00', max_length=10),
        ),
        migrations.AddField(
            model_name='proposta',
            name='tipo_faturamento',
            field=models.CharField(choices=[('imediato', 'Imediato na aprovação'), ('apos_execucao', 'Após execução'), ('parcelado', 'Parcelado')], default='imediato', max_length=20),
        ),
    ]
