# Generated by Django 6.0.5 on 2026-07-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0013_proposta_gera_conta_receber_automaticamente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='prazo_execucao',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
