# Generated by Django 6.0.5 on 2026-07-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0014_proposta_prazo_execucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='prazo_execucao',
            field=models.CharField(blank=True, default='10 dias úteis', max_length=200, verbose_name='Prazo para atendimento'),
        ),
    ]
