# Generated by Django 6.0.5 on 2026-07-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0015_alter_proposta_prazo_execucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='desconto_geral',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Desconto geral'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='frete_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Frete'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='margem_percentual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='%', max_digits=5, verbose_name='Margem'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='outras_despesas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Outras despesas'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='seguro_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Seguro'),
        ),
    ]
