# Generated by Django 6.0.5 on 2026-07-08 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0016_proposta_desconto_geral_proposta_frete_valor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropostaMovimentacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('tipo', models.CharField(choices=[('criacao', 'Criacao'), ('alteracao', 'Alteracao'), ('revisao', 'Revisao'), ('financeiro', 'Financeiro'), ('crm', 'CRM'), ('outro', 'Outro')], default='alteracao', max_length=20, verbose_name='Tipo')),
                ('revisao', models.CharField(blank=True, max_length=10, verbose_name='Revisao')),
                ('descricao', models.TextField(verbose_name='Movimentacao')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='comercial.proposta', verbose_name='Proposta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposta_movimentacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimentacao da Proposta',
                'verbose_name_plural': 'Movimentacoes da Proposta',
                'ordering': ('-data',),
            },
        ),
    ]
