# Generated by Django 4.2 on 2026-05-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriafinanceira',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
