# Generated by Django 6.0.5 on 2026-06-05 19:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('comercial', '0002_alter_crmregistro_options_alter_crmticket_options_and_more'),
        ('financeiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='imposto',
            name='competencia',
            field=models.CharField(help_text='Formato MM/AAAA (ex.: 01/2026)', max_length=7),
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_pedido', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Número do pedido')),
                ('data_emissao', models.DateField(auto_now_add=True, verbose_name='Data de emissão')),
                ('prazo_entrega', models.DateField(blank=True, null=True, verbose_name='Prazo de entrega')),
                ('condicao_pagamento', models.CharField(blank=True, max_length=200, verbose_name='Condição de pagamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frete', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outros_custos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra', to='clientes.cliente', verbose_name='Fornecedor')),
                ('responsavel_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela compra')),
            ],
            options={
                'verbose_name': 'Pedido de Compra',
                'verbose_name_plural': 'Pedidos de Compra',
                'db_table': 'purchase_orders',
                'ordering': ('-data_emissao', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PedidoCompraItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=50, verbose_name='Código')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Quantidade')),
                ('unidade', models.CharField(default='UN', max_length=20, verbose_name='Unidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor unitário')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desconto (%)')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor total')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='financeiro.pedidocompra', verbose_name='Pedido')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra_itens', to='comercial.produtoservico', verbose_name='Produto/Serviço')),
            ],
            options={
                'verbose_name': 'Item do Pedido de Compra',
                'verbose_name_plural': 'Itens do Pedido de Compra',
                'db_table': 'purchase_order_items',
                'ordering': ('id',),
            },
        ),
    ]
