# Generated by Django 6.0.5 on 2026-07-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_alter_imposto_competencia_pedidocompra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocompra',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='financeiro/pedidos_compra/', verbose_name='Anexo'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='incluir_nome_anexo_pdf',
            field=models.BooleanField(default=False, verbose_name='Incluir nome do anexo no PDF'),
        ),
    ]
