# Generated by Django 4.2 on 2026-05-17 06:23

from django.db import migrations, models
import django.db.models.deletion


def preencher_codigos_categoria(apps, schema_editor):
    categoria = apps.get_model("financeiro", "CategoriaFinanceira")

    for indice, item in enumerate(categoria.objects.order_by("nome"), start=1):
        if not item.codigo:
            item.codigo = f"CAT-{indice:04d}"
            item.save(update_fields=["codigo"])


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_remove_produtoservico_codigo_personalizado_and_more'),
        ('clientes', '0006_remove_cliente_fax_cliente_anexo_cliente_nome_anexo'),
        ('financeiro', '0002_categoriafinanceira_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriafinanceira',
            options={'ordering': ('codigo', 'nome'), 'verbose_name': 'Categoria Financeira', 'verbose_name_plural': 'Categorias Financeiras'},
        ),
        migrations.AddField(
            model_name='categoriafinanceira',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(preencher_codigos_categoria, migrations.RunPython.noop),
        migrations.AddField(
            model_name='contareceber',
            name='proposta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber', to='comercial.proposta'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='cliente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='descricao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
    ]
