# Generated by Django 6.0.5 on 2026-07-05 20:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0026_alter_calibracaopressao_tipo_instrumento'),
        ('clientes', '0002_alter_perfilusuario_empresa'),
        ('comercial', '0016_proposta_desconto_geral_proposta_frete_valor_and_more'),
        ('financeiro', '0003_pedidocompra_anexo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_nota', models.CharField(choices=[('venda_produto', 'Venda de Produto'), ('prestacao_servico', 'Prestacao de Servico'), ('venda_produto_servico', 'Venda de Produto + Servico'), ('entrada_compra', 'Entrada / Compra'), ('devolucao_compra', 'Devolucao de Compra'), ('devolucao_venda', 'Devolucao de Venda'), ('remessa_conserto', 'Remessa para Conserto'), ('retorno_conserto', 'Retorno de Conserto'), ('remessa_calibracao', 'Remessa para Calibracao'), ('retorno_calibracao', 'Retorno de Calibracao'), ('simples_remessa', 'Simples Remessa'), ('entrada_equipamento_cliente', 'Entrada de Equipamento de Cliente'), ('saida_devolucao_equipamento_cliente', 'Saida / Devolucao de Equipamento ao Cliente'), ('documento_interno_sem_nf', 'Documento Interno sem Nota Fiscal'), ('outro', 'Outro')], max_length=50, verbose_name='Tipo da nota')),
                ('fornecedor_nome', models.CharField(blank=True, max_length=255, verbose_name='Fornecedor')),
                ('fornecedor_cnpj', models.CharField(blank=True, max_length=20, verbose_name='CNPJ do fornecedor')),
                ('numero', models.CharField(blank=True, max_length=50, verbose_name='Numero')),
                ('serie', models.CharField(blank=True, max_length=50, verbose_name='Serie')),
                ('chave_acesso', models.CharField(blank=True, max_length=80, verbose_name='Chave de acesso')),
                ('natureza_operacao', models.CharField(blank=True, max_length=255, verbose_name='Natureza da operacao')),
                ('cfop', models.CharField(blank=True, max_length=20, verbose_name='CFOP')),
                ('codigo_servico', models.CharField(blank=True, max_length=50, verbose_name='Codigo do servico')),
                ('municipio_emissao', models.CharField(blank=True, max_length=120, verbose_name='Municipio de emissao')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de emissao')),
                ('data_entrada_saida', models.DateField(blank=True, null=True, verbose_name='Data de entrada/saida')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de vencimento')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor total')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('cadastrada', 'Cadastrada'), ('emitida_externa', 'Emitida em plataforma externa'), ('recebida', 'Recebida'), ('cancelada', 'Cancelada'), ('substituida', 'Substituida'), ('aguardando_pdf', 'Aguardando PDF'), ('aguardando_xml', 'Aguardando XML'), ('finalizada', 'Finalizada')], default='rascunho', max_length=30, verbose_name='Status')),
                ('status_operacional', models.CharField(choices=[('nao_aplicavel', 'Nao aplicavel'), ('aguardando_envio', 'Aguardando envio'), ('em_transito', 'Em transito'), ('recebido', 'Recebido'), ('em_analise', 'Em analise'), ('em_manutencao', 'Em manutencao'), ('em_calibracao', 'Em calibracao'), ('aguardando_retorno', 'Aguardando retorno'), ('retornado', 'Retornado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='nao_aplicavel', max_length=30, verbose_name='Status operacional')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='financeiro/notas_fiscais/pdf/', verbose_name='PDF / DANFE')),
                ('xml', models.FileField(blank=True, null=True, upload_to='financeiro/notas_fiscais/xml/', verbose_name='XML')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('calibracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='calibracao.calibracao', verbose_name='Calibracao')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='clientes.cliente', verbose_name='Cliente')),
                ('conta_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='financeiro.contapagar', verbose_name='Conta a pagar')),
                ('conta_receber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='financeiro.contareceber', verbose_name='Conta a receber')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('nota_referenciada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_relacionadas', to='financeiro.notafiscal', verbose_name='Nota referenciada')),
                ('pedido_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='financeiro.pedidocompra', verbose_name='Pedido de compra')),
                ('proposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='comercial.proposta', verbose_name='Proposta')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'ordering': ('-data_emissao', '-criado_em'),
            },
        ),
        migrations.CreateModel(
            name='ItemNotaFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_item', models.CharField(choices=[('produto', 'Produto'), ('servico', 'Servico'), ('equipamento_cliente', 'Equipamento de Cliente'), ('peca', 'Peca'), ('insumo', 'Insumo'), ('outro', 'Outro')], default='produto', max_length=30, verbose_name='Tipo do item')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descricao')),
                ('codigo_interno', models.CharField(blank=True, max_length=80, verbose_name='Codigo interno')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Quantidade')),
                ('unidade', models.CharField(default='UN', max_length=20, verbose_name='Unidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor unitario')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor total')),
                ('cfop', models.CharField(blank=True, max_length=20, verbose_name='CFOP')),
                ('ncm', models.CharField(blank=True, max_length=30, verbose_name='NCM')),
                ('codigo_servico', models.CharField(blank=True, max_length=50, verbose_name='Codigo do servico')),
                ('marca', models.CharField(blank=True, max_length=120, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=120, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=120, verbose_name='Numero de serie')),
                ('patrimonio', models.CharField(blank=True, max_length=120, verbose_name='Patrimonio')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='financeiro.notafiscal', verbose_name='Nota fiscal')),
            ],
            options={
                'verbose_name': 'Item da Nota Fiscal',
                'verbose_name_plural': 'Itens da Nota Fiscal',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='AnexoNotaFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='financeiro/notas_fiscais/anexos/', verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descricao')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='financeiro.notafiscal', verbose_name='Nota fiscal')),
            ],
            options={
                'verbose_name': 'Anexo da Nota Fiscal',
                'verbose_name_plural': 'Anexos da Nota Fiscal',
                'ordering': ('-criado_em',),
            },
        ),
    ]
