# Generated by Django 4.2 on 2026-05-17 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_remove_produtoservico_codigo_personalizado_and_more'),
        ('financeiro', '0003_alter_categoriafinanceira_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriafinanceira',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='categoriafinanceira',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='categoriafinanceira',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='data_recebimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de recebimento'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='proposta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber', to='comercial.proposta', verbose_name='Proposta aprovada'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('recebido', 'Recebido'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='vencimento',
            field=models.DateField(verbose_name='Vencimento'),
        ),
    ]
