# Generated by Django 6.0.5 on 2026-07-07 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_notafiscal_itemnotafiscal_anexonotafiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='pedido_compra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conta_pagar_gerada', to='financeiro.pedidocompra', verbose_name='Pedido de compra'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='vencimento_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento da conta a pagar'),
        ),
    ]
