# Generated by Django 6.0.5 on 2026-05-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('procedimento', 'Procedimento'), ('instrucao', 'Instrução'), ('norma', 'Norma'), ('metodo', 'Método'), ('formulario', 'Formulário'), ('outros', 'Outros')], max_length=30)),
                ('arquivo', models.FileField(upload_to='documentos/')),
            ],
        ),
    ]
