# Generated by Django 4.2 on 2026-03-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoQualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('procedimento', 'Procedimento'), ('instrucao', 'Instrução'), ('norma', 'Norma'), ('metodo', 'Método'), ('formulario', 'Formulário'), ('outros', 'Outros')], max_length=30)),
                ('arquivo', models.FileField(upload_to='qualidade/')),
            ],
        ),
    ]
