# Generated by Django 6.0.5 on 2026-06-08 03:57

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ('titulo', 'codigo'), 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AddField(
            model_name='documento',
            name='aprovado_por',
            field=models.CharField(default='Diego', max_length=100),
        ),
        migrations.AddField(
            model_name='documento',
            name='area',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='documento',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='documento',
            name='data_emissao',
            field=models.DateField(default=datetime.date(2026, 1, 1)),
        ),
        migrations.AddField(
            model_name='documento',
            name='data_ultima_revisao',
            field=models.DateField(default=datetime.date(2026, 1, 1)),
        ),
        migrations.AddField(
            model_name='documento',
            name='observacoes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='documento',
            name='obsoleto_motivo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='documento',
            name='prazo_revisao_meses',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='documento',
            name='responsavel',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='documento',
            name='revisao',
            field=models.CharField(default='REV.01', max_length=10),
        ),
        migrations.AddField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('em_elaboracao', 'Em elaboração'), ('em_revisao', 'Em revisão'), ('vigente', 'Vigente'), ('obsoleto', 'Obsoleto')], default='vigente', max_length=20),
        ),
        migrations.AddField(
            model_name='documento',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='documento',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='DocumentoRevisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisao', models.CharField(max_length=10)),
                ('data', models.DateField(default=datetime.date(2026, 1, 1))),
                ('alteracao', models.TextField()),
                ('responsavel', models.CharField(default='DS Científica', max_length=100)),
                ('status', models.CharField(choices=[('em_elaboracao', 'Em elaboração'), ('em_revisao', 'Em revisão'), ('vigente', 'Vigente'), ('obsoleto', 'Obsoleto')], default='vigente', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_revisoes', to='qualidade.documento')),
            ],
            options={
                'verbose_name': 'Histórico de revisão',
                'verbose_name_plural': 'Históricos de revisão',
                'ordering': ('-data', '-created_at'),
            },
        ),
    ]
