# Generated by Django 6.0.5 on 2026-07-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0002_alter_documento_options_documento_aprovado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='arquivo_rascunho_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documentos/rascunhos/'),
        ),
    ]
