# Generated by Django 4.2 on 2026-05-12 21:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0006_remove_cliente_fax_cliente_anexo_cliente_nome_anexo'),
        ('qualidade', '0002_documento_delete_documentoqualidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('local_instalacao', models.CharField(blank=True, max_length=200)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('manutencao', 'Em Manutenção')], default='ativo', max_length=20)),
                ('proxima_calibracao', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome_anexo', models.CharField(blank=True, max_length=200)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='instrumentos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrumentos', to='clientes.cliente')),
                ('metodo_calibracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrumentos', to='qualidade.documento')),
            ],
        ),
        migrations.CreateModel(
            name='Padrao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('valido', 'Válido'), ('vencido', 'Vencido'), ('suspenso', 'Suspenso')], default='valido', max_length=20)),
                ('vencimento', models.DateField()),
                ('certificado', models.FileField(blank=True, null=True, upload_to='padroes/')),
            ],
        ),
        migrations.CreateModel(
            name='Periodicidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('calibracao', 'Calibração'), ('manutencao', 'Manutenção')], max_length=20)),
                ('intervalo_meses', models.PositiveIntegerField()),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodicidades', to='calibracao.instrumento')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50)),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='ordens_servico/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa_medicao', models.CharField(blank=True, max_length=100)),
                ('unidade', models.CharField(blank=True, max_length=50)),
                ('classe', models.CharField(blank=True, max_length=50)),
                ('observacoes', models.TextField(blank=True)),
                ('instrumento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tecnico', to='calibracao.instrumento')),
            ],
        ),
        migrations.AddField(
            model_name='instrumento',
            name='padroes',
            field=models.ManyToManyField(blank=True, related_name='instrumentos', to='calibracao.padrao'),
        ),
        migrations.CreateModel(
            name='Calibracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_calibracao', models.DateField()),
                ('validade', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('resultado', models.CharField(choices=[('aprovado', 'Aprovado'), ('ressalva', 'Aprovado com ressalva'), ('reprovado', 'Reprovado')], default='aprovado', max_length=20)),
                ('certificado_numero', models.CharField(blank=True, max_length=100)),
                ('certificado_arquivo', models.FileField(blank=True, null=True, upload_to='calibracoes/')),
                ('empresa_emissora', models.CharField(blank=True, max_length=200)),
                ('metodo', models.TextField(blank=True)),
                ('padroes', models.TextField(blank=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('umidade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('local_calibracao', models.CharField(choices=[('laboratorio', 'DS Científica'), ('in_loco', 'In Loco')], default='laboratorio', max_length=20)),
                ('equipamentos_auxiliares', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibracoes', to='calibracao.instrumento')),
            ],
        ),
    ]
