# Generated by Django 4.2 on 2026-05-13 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibracaoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='calibracao/anexos/')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('calibracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='calibracao.calibracao')),
            ],
        ),
    ]
