# Generated by Django 6.0.5 on 2026-06-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calibracao',
            options={'verbose_name': 'Calibração', 'verbose_name_plural': 'Calibrações'},
        ),
        migrations.AlterModelOptions(
            name='padrao',
            options={'verbose_name': 'Padrão', 'verbose_name_plural': 'Padrões'},
        ),
        migrations.AlterField(
            model_name='calibracao',
            name='local_calibracao',
            field=models.CharField(choices=[('laboratorio', 'DS Científica'), ('in_loco', 'In loco')], default='laboratorio', max_length=20),
        ),
    ]
