# Generated by Django 4.2 on 2026-05-17 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_remove_cliente_fax_cliente_anexo_cliente_nome_anexo'),
        ('comercial', '0006_remove_produtoservico_codigo_personalizado_and_more'),
        ('calibracao', '0002_calibracaoanexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='instrumentos',
            field=models.ManyToManyField(blank=True, related_name='ordens_servico', to='calibracao.instrumento'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='proposta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='comercial.proposta'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='cliente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='clientes.cliente'),
        ),
    ]
