# Generated by Django 4.2 on 2026-05-17 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_remove_produtoservico_codigo_personalizado_and_more'),
        ('calibracao', '0003_ordemservico_data_conclusao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemservico',
            options={'verbose_name': 'Ordem de Serviço', 'verbose_name_plural': 'Ordens de Serviço'},
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='data_abertura',
            field=models.DateField(auto_now_add=True, verbose_name='Data de abertura'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de conclusão'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='instrumentos',
            field=models.ManyToManyField(blank=True, related_name='ordens_servico', to='calibracao.instrumento', verbose_name='Equipamentos'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='numero',
            field=models.CharField(max_length=50, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='proposta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='comercial.proposta', verbose_name='Proposta'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=20, verbose_name='Status'),
        ),
    ]
