# Generated by Django 6.0.5 on 2026-06-09 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0003_calibracaoturbidez_turbidezcalibracaoponto_and_more'),
        ('qualidade', '0002_alter_documento_options_documento_aprovado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibracaoturbidez',
            name='procedimento_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibracoes_turbidez', to='qualidade.documento'),
        ),
    ]
