# Generated by Django 6.0.5 on 2026-06-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0004_calibracaoturbidez_procedimento_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentotecnico',
            name='capacidade_total',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='instrumentotecnico',
            name='menor_resolucao',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
