# Generated by Django 6.0.5 on 2026-06-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0005_instrumentotecnico_capacidade_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turbidezpadraoutilizado',
            name='data_calibracao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
