# Generated by Django 6.0.5 on 2026-06-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0006_turbidezpadraoutilizado_data_calibracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='padrao',
            name='data_calibracao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='padrao',
            name='fator_k',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='padrao',
            name='graus_liberdade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='padrao',
            name='incerteza',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='padrao',
            name='laboratorio_emitente',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='padrao',
            name='numero_certificado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='padrao',
            name='resolucao',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='padrao',
            name='unidade',
            field=models.CharField(blank=True, default='NTU', max_length=30),
        ),
        migrations.AddField(
            model_name='padrao',
            name='valor_nominal',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='calibracaoturbidez',
            name='local_calibracao',
            field=models.CharField(choices=[('in_loco', 'IN LOCO'), ('laboratorio_optico_ds', 'Laboratório Óptico DS Científica'), ('ds_cientifica', 'DS Científica')], default='ds_cientifica', max_length=30),
        ),
    ]
