# Generated by Django 6.0.5 on 2026-06-09 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0007_padrao_data_calibracao_padrao_fator_k_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilIncertezaTurbidez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('resolucao_instrumento', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('resolucao_padrao', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('incerteza_padrao', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('incerteza_curva', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('incerteza_turbidimetro', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('instrumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis_incerteza_turbidez', to='calibracao.instrumento')),
                ('padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis_incerteza_turbidez', to='calibracao.padrao')),
            ],
            options={
                'verbose_name': 'Perfil de incerteza de turbidez',
                'verbose_name_plural': 'Perfis de incerteza de turbidez',
                'ordering': ('nome',),
            },
        ),
        migrations.AddField(
            model_name='calibracaoturbidez',
            name='perfil_incerteza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibracoes', to='calibracao.perfilincertezaturbidez'),
        ),
    ]
