# Generated by Django 6.0.5 on 2026-06-09 05:41

from django.db import migrations


def create_default_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    def perms_for(models_by_app, actions):
        query = None
        for app_label, models in models_by_app.items():
            for model in models:
                codenames = [f"{action}_{model}" for action in actions]
                current = Permission.objects.filter(
                    content_type__app_label=app_label,
                    content_type__model=model,
                    codename__in=codenames,
                )
                query = current if query is None else (query | current)
        return query.distinct() if query is not None else Permission.objects.none()

    all_business_models = {
        "clientes": ["cliente", "contatocliente", "clienteanexo", "perfilusuario"],
        "comercial": [
            "produtoservico",
            "composicaopreco",
            "dadostecnicos",
            "produtoanexo",
            "proposta",
            "propostaanexo",
            "itemproposta",
            "crmregistro",
            "crminteracao",
            "crmticket",
        ],
        "financeiro": [
            "categoriafinanceira",
            "contapagar",
            "contareceber",
            "imposto",
            "pedidocompra",
            "pedidocompraitem",
        ],
        "calibracao": [
            "instrumento",
            "instrumentotecnico",
            "ordemservico",
            "padrao",
            "periodicidade",
            "calibracao",
            "calibracaoanexo",
            "calibracaoturbidez",
            "turbidezpadraoutilizado",
            "turbidezverificacaoponto",
            "turbidezcalibracaoponto",
            "turbidezincertezaponto",
        ],
        "qualidade": ["documento", "documentorevisao"],
    }

    group_definitions = {
        "Administrador": {
            "models": {
                **all_business_models,
                "auth": ["user", "group"],
            },
            "actions": ("view", "add", "change", "delete"),
        },
        "Comercial": {
            "models": {
                "clientes": ["cliente", "contatocliente"],
                "comercial": [
                    "produtoservico",
                    "composicaopreco",
                    "dadostecnicos",
                    "produtoanexo",
                    "proposta",
                    "propostaanexo",
                    "itemproposta",
                    "crmregistro",
                    "crminteracao",
                    "crmticket",
                ],
            },
            "actions": ("view", "add", "change"),
        },
        "Financeiro": {
            "models": {
                "clientes": ["cliente", "contatocliente"],
                "comercial": ["proposta", "itemproposta"],
                "financeiro": [
                    "categoriafinanceira",
                    "contapagar",
                    "contareceber",
                    "imposto",
                    "pedidocompra",
                    "pedidocompraitem",
                ],
            },
            "actions": ("view", "add", "change"),
        },
        "Metrologia": {
            "models": {
                "clientes": ["cliente", "contatocliente"],
                "qualidade": ["documento"],
                "calibracao": [
                    "instrumento",
                    "instrumentotecnico",
                    "ordemservico",
                    "padrao",
                    "periodicidade",
                    "calibracao",
                    "calibracaoanexo",
                    "calibracaoturbidez",
                    "turbidezpadraoutilizado",
                    "turbidezverificacaoponto",
                    "turbidezcalibracaoponto",
                    "turbidezincertezaponto",
                ],
            },
            "actions": ("view", "add", "change"),
        },
        "Qualidade": {
            "models": {
                "qualidade": ["documento", "documentorevisao"],
                "calibracao": ["padrao"],
            },
            "actions": ("view", "add", "change"),
        },
        "Consulta": {
            "models": all_business_models,
            "actions": ("view",),
        },
    }

    for group_name, config in group_definitions.items():
        group, _ = Group.objects.get_or_create(name=group_name)
        group.permissions.set(perms_for(config["models"], config["actions"]))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ('calibracao', '0008_perfilincertezaturbidez_and_more'),
        ("clientes", "0001_initial"),
        ("comercial", "0002_alter_crmregistro_options_alter_crmticket_options_and_more"),
        ("financeiro", "0002_alter_imposto_competencia_pedidocompra_and_more"),
        ("qualidade", "0002_alter_documento_options_documento_aprovado_por_and_more"),
    ]

    operations = [
        migrations.RunPython(create_default_groups, noop_reverse),
    ]
