# Generated by Django 6.0.5 on 2026-06-09 18:20

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0009_create_default_access_groups'),
        ('clientes', '0001_initial'),
        ('qualidade', '0002_alter_documento_options_documento_aprovado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibracaoColorimetro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_aplicacao', models.CharField(choices=[('cloro', 'Cloro'), ('fluor', 'Flúor'), ('cor', 'Cor'), ('fotocolorimetro', 'Fotocolorímetro')], default='cloro', max_length=30)),
                ('numero_certificado', models.CharField(blank=True, max_length=100, unique=True)),
                ('ordem_servico', models.CharField(blank=True, max_length=100)),
                ('data_calibracao', models.DateField()),
                ('data_emissao', models.DateField(default=datetime.date.today)),
                ('revisao', models.CharField(blank=True, default='00', max_length=20)),
                ('local_calibracao', models.CharField(choices=[('in_loco', 'IN LOCO'), ('laboratorio_optico_ds', 'Laboratório Óptico DS Científica'), ('ds_cientifica', 'DS Científica')], default='ds_cientifica', max_length=30)),
                ('contratante', models.CharField(blank=True, max_length=255)),
                ('endereco_contratante', models.CharField(blank=True, max_length=255)),
                ('endereco_cliente', models.CharField(blank=True, max_length=255)),
                ('equipamento_calibrado', models.CharField(blank=True, default='Colorímetro', max_length=255)),
                ('numero_identificacao', models.CharField(blank=True, max_length=100)),
                ('capacidade_total', models.CharField(blank=True, max_length=100)),
                ('faixa_calibrada', models.CharField(blank=True, max_length=100)),
                ('menor_resolucao', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('unidade_leitura', models.CharField(blank=True, max_length=50)),
                ('procedimento_numero', models.CharField(blank=True, max_length=100)),
                ('procedimento_revisao', models.CharField(blank=True, max_length=50)),
                ('temperatura_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('umidade_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('umidade_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ajuste_efetuado', models.BooleanField(default=False)),
                ('tecnico_responsavel', models.CharField(blank=True, max_length=255)),
                ('responsavel_conferencia', models.CharField(blank=True, max_length=255)),
                ('signatario_autorizado', models.CharField(blank=True, max_length=255)),
                ('funcao_signatario', models.CharField(blank=True, max_length=255)),
                ('observacoes_certificado', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibracoes_colorimetro', to='clientes.cliente')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibracoes_colorimetro', to='calibracao.instrumento')),
                ('procedimento_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibracoes_colorimetro', to='qualidade.documento')),
            ],
            options={
                'verbose_name': 'Calibração de Colorímetro',
                'verbose_name_plural': 'Calibrações de Colorímetro',
                'ordering': ('-data_calibracao', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ColorimetroCalibracaoPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('valor_referencia', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('leitura_1', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('leitura_2', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('leitura_3', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('resolucao', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('media', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('desvio_padrao', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('erro', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('ema', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('criterio', models.CharField(blank=True, max_length=120)),
                ('calibracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_calibracao', to='calibracao.calibracaocolorimetro')),
            ],
            options={
                'verbose_name': 'Ponto de calibração',
                'verbose_name_plural': 'Pontos de calibração',
                'ordering': ('ordem',),
            },
        ),
        migrations.CreateModel(
            name='ColorimetroIncertezaPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('repetibilidade', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('resolucao_instrumento', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('incerteza_padrao', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('resolucao_padrao', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('incerteza_curva', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('fator_k', models.DecimalField(decimal_places=3, default=2, max_digits=8)),
                ('graus_liberdade', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('incerteza_padrao_combinada', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('incerteza_expandida', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('calibracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_incerteza', to='calibracao.calibracaocolorimetro')),
            ],
            options={
                'verbose_name': 'Ponto de incerteza',
                'verbose_name_plural': 'Pontos de incerteza',
                'ordering': ('ordem',),
            },
        ),
        migrations.CreateModel(
            name='ColorimetroPadraoUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('verificacao', 'Padrões da verificação'), ('calibracao', 'Padrões da calibração'), ('termometro', 'Termômetro ambiente'), ('higrometro', 'Higrômetro ambiente')], max_length=30)),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('codigo', models.CharField(blank=True, max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('numero_certificado', models.CharField(blank=True, max_length=100)),
                ('laboratorio_emitente', models.CharField(blank=True, max_length=150)),
                ('data_calibracao', models.DateField(blank=True, null=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('resolucao', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('rastreabilidade', models.CharField(blank=True, max_length=100)),
                ('incerteza', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('fator_k', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('graus_liberdade', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unidade', models.CharField(blank=True, max_length=30)),
                ('valor_nominal', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('calibracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padroes_utilizados', to='calibracao.calibracaocolorimetro')),
                ('padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos_colorimetro', to='calibracao.padrao')),
            ],
            options={
                'verbose_name': 'Padrão utilizado',
                'verbose_name_plural': 'Padrões utilizados',
                'ordering': ('tipo', 'ordem'),
            },
        ),
        migrations.CreateModel(
            name='ColorimetroVerificacaoPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('valor_padrao', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('leitura', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('erro', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('criterio', models.CharField(blank=True, max_length=120)),
                ('resultado', models.CharField(blank=True, max_length=50)),
                ('calibracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_verificacao', to='calibracao.calibracaocolorimetro')),
            ],
            options={
                'verbose_name': 'Ponto de verificação',
                'verbose_name_plural': 'Pontos de verificação',
                'ordering': ('ordem',),
            },
        ),
    ]
