# Generated by Django 6.0.5 on 2026-06-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0010_calibracaocolorimetro_colorimetrocalibracaoponto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibracaoturbidez',
            name='resultado_final',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='colorimetrocalibracaoponto',
            name='criterio_referencia',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='colorimetroverificacaoponto',
            name='criterio_referencia',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
