# Generated by Django 6.0.5 on 2026-06-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0011_calibracaoturbidez_resultado_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibracaocolorimetro',
            name='resultado_final',
            field=models.TextField(blank=True),
        ),
    ]
