# Generated by Django 6.0.5 on 2026-06-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0012_calibracaocolorimetro_resultado_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibracaocolorimetro',
            name='resultado_final_status',
            field=models.CharField(blank=True, choices=[('', '---------'), ('conforme', 'Equipamento conforme, dentro do critério de aceitação informado'), ('nao_conforme', 'Equipamento não conforme, fora do critério de aceitação informado')], max_length=30),
        ),
        migrations.AddField(
            model_name='colorimetrocalibracaoponto',
            name='criterio_origem',
            field=models.CharField(blank=True, choices=[('', '---------'), ('cliente', 'Cliente'), ('fabricante', 'Fabricante')], max_length=30),
        ),
        migrations.AddField(
            model_name='colorimetroverificacaoponto',
            name='criterio_origem',
            field=models.CharField(blank=True, choices=[('', '---------'), ('cliente', 'Cliente'), ('fabricante', 'Fabricante')], max_length=30),
        ),
    ]
