# Generated by Django 6.0.5 on 2026-06-09 20:19

import django.db.models.deletion
from django.db import migrations, models


def criar_responsavel_padrao(apps, schema_editor):
    ResponsavelCertificado = apps.get_model('calibracao', 'ResponsavelCertificado')
    ResponsavelCertificado.objects.get_or_create(
        nome='Diego Henrique Alves Saldanha',
        defaults={'cargo': 'Responsável técnico', 'ativo': True},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0013_calibracaocolorimetro_resultado_final_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsavelCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('cargo', models.CharField(blank=True, default='Responsável técnico', max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Responsável de certificado',
                'verbose_name_plural': 'Responsáveis de certificado',
                'ordering': ('nome',),
            },
        ),
        migrations.AddField(
            model_name='calibracaocolorimetro',
            name='responsavel_tecnico_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibracoes_colorimetro_como_responsavel', to='calibracao.responsavelcertificado'),
        ),
        migrations.AddField(
            model_name='calibracaocolorimetro',
            name='tecnico_executante_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibracoes_colorimetro_como_executante', to='calibracao.responsavelcertificado'),
        ),
        migrations.AddField(
            model_name='calibracaoturbidez',
            name='responsavel_tecnico_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibracoes_turbidez_como_responsavel', to='calibracao.responsavelcertificado'),
        ),
        migrations.AddField(
            model_name='calibracaoturbidez',
            name='tecnico_executante_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibracoes_turbidez_como_executante', to='calibracao.responsavelcertificado'),
        ),
        migrations.RunPython(criar_responsavel_padrao, migrations.RunPython.noop),
    ]
