# Generated by Django 6.0.5 on 2026-06-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0015_calibracaopressao_pressaocalibracaoponto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibracaopressao',
            name='tipo_instrumento',
            field=models.CharField(choices=[('manometro', 'Manômetro'), ('transmissor', 'Transmissor de pressão'), ('indicador_transmissor', 'Indicador e transmissor de pressão'), ('vacuometro', 'Vacuômetro'), ('manovacuometro', 'Manovacuômetro'), ('pressostato', 'Pressostato')], default='manometro', max_length=30),
        ),
    ]
