# Generated by Django 6.0.5 on 2026-06-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0016_alter_calibracaopressao_tipo_instrumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressaocalibracaoponto',
            name='criterio_origem',
            field=models.CharField(blank=True, choices=[('', '---------'), ('cliente', 'Tolerância do cliente'), ('fabricante', 'Tolerância do fabricante')], max_length=30),
        ),
        migrations.AddField(
            model_name='pressaocalibracaoponto',
            name='criterio_referencia',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='calibracaopressao',
            name='local_calibracao',
            field=models.CharField(choices=[('in_loco', 'IN LOCO'), ('laboratorio_pressao_ds', 'Laboratório Pressão DS Científica'), ('ds_cientifica', 'DS Científica')], default='ds_cientifica', max_length=30),
        ),
    ]
