# Generated by Django 6.0.5 on 2026-06-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0017_pressaocalibracaoponto_criterio_origem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibracaopressao',
            name='local_calibracao',
            field=models.CharField(choices=[('in_loco', 'IN LOCO'), ('laboratorio_optico_ds', 'Laboratório Pressão DS Científica'), ('laboratorio_pressao_ds', 'Laboratório Pressão DS Científica'), ('ds_cientifica', 'DS Científica')], default='ds_cientifica', max_length=30),
        ),
    ]
