# Generated by Django 6.0.5 on 2026-06-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0019_alter_pressaocalibracaoponto_criterio_origem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressaocalibracaoponto',
            name='criterio_origem',
            field=models.CharField(blank=True, choices=[('', '---------'), ('cliente', 'Tolerância do cliente'), ('fabricante', 'Tolerância do fabricante')], default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pressaocalibracaoponto',
            name='criterio_referencia',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
