# Generated by Django 6.0.5 on 2026-06-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0021_calibracaoph_calibracaophincertezaponto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibracaoph',
            name='slope_indicado',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='calibracaoph',
            name='tipo_calibracao',
            field=models.CharField(choices=[('calibracao_eletrica', 'Calibração elétrica'), ('calibracao_ph_simples', 'Calibração pH simples'), ('calibracao_ph_completa', 'Calibração pH completa')], default='eletrica_ph', max_length=30),
        ),
        migrations.AlterField(
            model_name='calibracaophponto',
            name='tipo',
            field=models.CharField(choices=[('eletrica_mv', 'Eletrica em mV'), ('eletrica_ph', 'Eletrica em pH'), ('quimica_acida', 'Quimica acida'), ('quimica_neutra', 'Quimica neutra'), ('quimica_basica', 'Quimica basica'), ('verificacao_acida', 'Verificacao acida'), ('verificacao_basica', 'Verificacao basica'), ('mrc_acida', 'MRC acida'), ('mrc_neutra', 'MRC neutra'), ('mrc_basica', 'MRC basica'), ('mrc_verificacao_acida', 'MRC verificacao acida'), ('mrc_verificacao_basica', 'MRC verificacao basica')], max_length=30),
        ),
    ]
