# Generated by Django 6.0.5 on 2026-06-24 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0022_calibracaoph_slope_indicado_and_more'),
        ('clientes', '0002_alter_perfilusuario_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibracaoCondutividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_servico', models.CharField(blank=True, max_length=50)),
                ('numero_certificado', models.CharField(max_length=80, unique=True)),
                ('revisao', models.CharField(blank=True, max_length=20)),
                ('data_calibracao', models.DateField()),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('local_calibracao', models.CharField(choices=[('laboratorio', 'Laboratório'), ('externo', 'Externo')], default='laboratorio', max_length=20)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_analise', 'Em análise'), ('emitida', 'Emitida'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20)),
                ('resultado_final', models.CharField(choices=[('aprovado', 'Aprovado'), ('aprovado_ressalva', 'Aprovado com ressalva'), ('reprovado', 'Reprovado')], default='aprovado', max_length=30)),
                ('contratante', models.CharField(blank=True, max_length=255)),
                ('endereco_contratante', models.CharField(blank=True, max_length=255)),
                ('endereco_cliente', models.CharField(blank=True, max_length=255)),
                ('equipamento_calibrado', models.CharField(blank=True, max_length=255)),
                ('numero_identificacao', models.CharField(blank=True, max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('faixa_capacidade', models.CharField(blank=True, max_length=120)),
                ('resolucao', models.CharField(blank=True, max_length=50)),
                ('unidade_indicacao', models.CharField(blank=True, default='mS/cm', max_length=20)),
                ('unidade_padrao', models.CharField(blank=True, default='mS/cm', max_length=20)),
                ('unidade_leitura', models.CharField(blank=True, default='mS/cm', max_length=20)),
                ('temperatura_referencia', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('identificacao_celula', models.CharField(blank=True, max_length=100)),
                ('constante_celula', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('compensacao_temperatura', models.CharField(blank=True, max_length=100)),
                ('tecnico_responsavel', models.CharField(blank=True, max_length=255)),
                ('responsavel_conferencia', models.CharField(blank=True, max_length=255)),
                ('signatario_autorizado', models.CharField(blank=True, max_length=255)),
                ('funcao_signatario', models.CharField(blank=True, max_length=255)),
                ('temperatura_ambiente', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('umidade_ambiente', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('snapshot_json', models.JSONField(blank=True, default=dict)),
                ('pdf_arquivo', models.FileField(blank=True, null=True, upload_to='calibracoes/condutividade/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibracoes_condutividade', to='clientes.cliente')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibracoes_condutividade', to='calibracao.instrumento')),
            ],
            options={
                'verbose_name': 'Calibração de Condutividade',
                'verbose_name_plural': 'Calibrações de Condutividade',
                'ordering': ('-data_calibracao', '-created_at'),
            },
        ),
    ]
