# Generated by Django 6.0.5 on 2026-06-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0024_rebuild_calibracaocondutividade_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
