# Generated by Django 6.0.5 on 2026-07-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0025_instrumento_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibracaopressao',
            name='tipo_instrumento',
            field=models.CharField(choices=[('manometro', 'Manômetro'), ('transmissor', 'Transmissor de pressão'), ('indicador_transmissor', 'Indicador e transmissor de pressão'), ('vacuometro', 'Vacuômetro'), ('manovacuometro', 'Manovacuômetro'), ('pressostato', 'Pressostato'), ('valvula_seguranca', 'VÃ¡lvula de seguranÃ§a'), ('esfigmomanometro', 'EsfigmomanÃ´metro')], default='manometro', max_length=30),
        ),
    ]
