# Generated by Django 6.0.5 on 2026-07-07 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0026_alter_calibracaopressao_tipo_instrumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibracaocolorimetro',
            name='padrao_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibracoes_colorimetro_referencia', to='calibracao.padrao'),
        ),
    ]
