# Generated by Django 6.0.5 on 2026-06-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='empresa',
            field=models.CharField(blank=True, default='DS Científica', max_length=200),
        ),
    ]
