# Generated by Django 4.2 on 2026-03-25 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_codigo_clienteanexo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienteanexo',
            options={'ordering': ('-data_upload',)},
        ),
    ]
