# Generated by Django 4.2 on 2026-03-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_clienteanexo_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fax',
        ),
        migrations.AddField(
            model_name='cliente',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='clientes/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_anexo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
