# Generated by Django 6.0.5 on 2026-07-01 04:51

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qualidade', '0002_alter_documento_options_documento_aprovado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoFuncao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RH - Cargo e função',
                'verbose_name_plural': 'RH - Cargos e funções',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('socio', 'Sócio'), ('clt', 'CLT'), ('pj', 'PJ'), ('terceiro', 'Terceiro'), ('autonomo', 'Autônomo')], default='clt', max_length=20)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('afastado', 'Afastado'), ('ferias', 'Férias'), ('bloqueado', 'Bloqueado')], default='ativo', max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cidade_base', models.CharField(blank=True, max_length=120)),
                ('valor_hora_interna', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('valor_hora_venda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('custo_diaria', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('disponivel_campo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='gestao.cargofuncao')),
            ],
            options={
                'verbose_name': 'RH - Colaborador',
                'verbose_name_plural': 'RH - Colaboradores',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('treinamento', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], default='interno', max_length=20)),
                ('instrutor', models.CharField(blank=True, max_length=150)),
                ('carga_horaria', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('data', models.DateField(blank=True, null=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='planejado', max_length=20)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='gestao/treinamentos/')),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinamentos', to='gestao.colaborador')),
            ],
            options={
                'verbose_name': 'RH - Treinamento',
                'verbose_name_plural': 'RH - Treinamentos',
                'ordering': ('-data', 'treinamento'),
            },
        ),
        migrations.CreateModel(
            name='CompetenciaTecnica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grandeza', models.CharField(max_length=120)),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado'), ('especialista', 'Especialista')], default='basico', max_length=20)),
                ('autorizado_executar', models.BooleanField(default=True)),
                ('necessita_supervisao', models.BooleanField(default=False)),
                ('data_habilitacao', models.DateField(blank=True, null=True)),
                ('validade_habilitacao', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='gestao.colaborador')),
                ('documento_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencias_tecnicas', to='qualidade.documento')),
            ],
            options={
                'verbose_name': 'RH - Competência técnica',
                'verbose_name_plural': 'RH - Competências técnicas',
                'ordering': ('colaborador__nome', 'grandeza'),
                'constraints': [models.UniqueConstraint(fields=('colaborador', 'grandeza'), name='unique_competencia_por_colaborador')],
            },
        ),
    ]
