# Generated by Django 6.0.5 on 2026-07-01 13:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColaboradorAnexo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('documento_pessoal', 'Documento pessoal'), ('aso', 'ASO'), ('contrato', 'Contrato'), ('certificado', 'Certificado'), ('treinamento', 'Evidencia de treinamento'), ('comprovante', 'Comprovante'), ('foto', 'Foto'), ('outro', 'Outro')], default='outro', max_length=30)),
                ('arquivo', models.FileField(upload_to='gestao/colaboradores/anexos/')),
                ('descricao', models.TextField(blank=True)),
                ('data_documento', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='gestao.colaborador')),
            ],
            options={
                'verbose_name': 'RH - Anexo do colaborador',
                'verbose_name_plural': 'RH - Anexos do colaborador',
                'ordering': ('-created_at', 'titulo'),
            },
        ),
    ]
