# Generated by Django 6.0.5 on 2026-07-03 03:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_colaboradoranexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('cartao_cnpj', 'Cartão CNPJ'), ('inscricao_estadual', 'Inscrição Estadual'), ('inscricao_municipal', 'Inscrição Municipal'), ('contrato_social', 'Contrato Social'), ('alvara', 'Alvará'), ('certidao', 'Certidão'), ('comprovante_endereco', 'Comprovante de Endereço'), ('bancario', 'Documento Bancário'), ('fiscal', 'Documento Fiscal'), ('licenca', 'Licença'), ('outro', 'Outro')], default='outro', max_length=30)),
                ('numero_identificacao', models.CharField(blank=True, max_length=80)),
                ('orgao_emissor', models.CharField(blank=True, max_length=120)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('vigente', 'Vigente'), ('vencendo', 'Vencendo'), ('vencido', 'Vencido'), ('inativo', 'Inativo')], default='vigente', max_length=20)),
                ('arquivo', models.FileField(upload_to='gestao/documentos_empresa/')),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gestão - Documento da empresa',
                'verbose_name_plural': 'Gestão - Documentos da empresa',
                'ordering': ('titulo', '-created_at'),
            },
        ),
    ]
