# Generated by Codex on 2026-06-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manutencao", "0005_manutencao_responsavel_cliente_ref"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManutencaoEvidencia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(blank=True, max_length=180)),
                ("arquivo", models.FileField(upload_to="manutencao/evidencias/%Y/%m/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manutencao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidencias",
                        to="manutencao.manutencao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidência da manutenção",
                "verbose_name_plural": "Evidências da manutenção",
                "ordering": ["id"],
            },
        ),
    ]
